// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type BillingAddress struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Street     string
	City       string
	State      string
	Country    string
	PostalCode string
}

type CartItem struct {
	ID             uuid.UUID
	ShoppingCartID uuid.UUID
	ProductID      uuid.UUID
	Quantity       int32
	CreatedAt      time.Time
	LastUpdated    sql.NullTime
}

type Category struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	ImageUrl    sql.NullString
	SeoKeywords sql.NullString
	IsActive    bool
	CreatedAt   time.Time
	LastUpdated sql.NullTime
}

type Colour struct {
	ID          uuid.UUID
	ColourHex   string
	CreatedAt   time.Time
	LastUpdated sql.NullTime
}

type Material struct {
	ID          uuid.UUID
	Name        string
	CreatedAt   time.Time
	LastUpdated sql.NullTime
}

type Order struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	OrderStatus     string
	PaymentStatus   string
	PaymentMethod   string
	ShippingAddress string
	BillingAddress  string
	TotalPrice      string
	CreatedAt       time.Time
	LastUpdated     sql.NullTime
}

type OrderItem struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	ProductID   uuid.UUID
	Quantity    int32
	TaxedPrice  string
	CreatedAt   time.Time
	LastUpdated sql.NullTime
}

type Product struct {
	ID            uuid.UUID
	Name          string
	Description   sql.NullString
	ImageUrl      sql.NullString
	Price         string
	Stock         int32
	Brand         sql.NullString
	Rating        string
	ReviewCount   int32
	DiscountRate  string
	Keywords      sql.NullString
	IsActive      bool
	CreatedAt     time.Time
	LastUpdated   sql.NullTime
	SubCategoryID uuid.NullUUID
}

type ProductColour struct {
	ID          uuid.UUID
	ProductID   uuid.UUID
	ColourID    uuid.UUID
	CreatedAt   time.Time
	LastUpdated sql.NullTime
}

type ProductMaterial struct {
	ID          uuid.UUID
	ProductID   uuid.UUID
	MaterialID  uuid.UUID
	CreatedAt   time.Time
	LastUpdated sql.NullTime
}

type RecentlyViewedProduct struct {
	UserID       uuid.UUID
	ProductID    uuid.UUID
	LastViewedAt time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Review struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ProductID   uuid.UUID
	Rating      string
	Comment     sql.NullString
	CreatedAt   time.Time
	LastUpdated sql.NullTime
}

type ShippingAddress struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Street     string
	City       string
	State      string
	Country    string
	PostalCode string
}

type ShoppingCart struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CreatedAt   time.Time
	LastUpdated sql.NullTime
	TotalItems  int32
	TotalPrice  string
}

type SubCategory struct {
	ID          uuid.UUID
	CategoryID  uuid.UUID
	Name        string
	Description sql.NullString
	ImageUrl    sql.NullString
	SeoKeywords sql.NullString
	IsActive    bool
	CreatedAt   time.Time
	LastUpdated sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	HashedPassword string
	FirstName      string
	LastName       string
	PhoneNumber    sql.NullString
	DateOfBirth    sql.NullTime
	Gender         sql.NullString
	CreatedAt      time.Time
	LastLogin      sql.NullTime
	AccountStatus  string
	UserRole       string
	ProfilePicture sql.NullString
	TwoFactorAuth  bool
}

type Wishlist struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Visibility  string
	CreatedAt   time.Time
	LastUpdated sql.NullTime
}

type WishlistItem struct {
	ID          uuid.UUID
	WishlistID  uuid.UUID
	ProductID   uuid.UUID
	Priority    string
	CreatedAt   time.Time
	LastUpdated sql.NullTime
}
